import {TeaItem,url} from './model';
import {Badge,Button,Icon} from './ui';

const history=[
  ['01','起源与利用','从认识植物与日常利用开始，茶逐渐进入生活记录。','一片叶'],
  ['02','制茶与分类','不同加工方式保留或转化叶片特征，形成各有特点的茶类。','成其味'],
  ['03','茶事与交流','器具、礼俗与地方经验，让饮茶成为人与人交流的方式。','见人情'],
  ['04','当代记录','用来源、版本与批次整理茶知识，让每份说明都有迹可循。','可查证']
];

export function HomeHistory(){return <section id="history" className="home-scroll-section history-section" tabIndex={-1} aria-labelledby="history-title"><div className="container"><div className="scroll-section-head"><div><div className="eyebrow">A SHORT HISTORY OF TEA / 茶的历史</div><h2 id="history-title">一片叶子，走过很长的时间</h2></div><p>这是一段用于理解茶文化脉络的概览。正式知识内容仍以经授权、可追溯的资料为准。</p></div><div className="history-line">{history.map(([n,title,desc,tag])=><article key={n}><div className="history-index"><span>{n}</span><i/></div><Badge>{tag}</Badge><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>}

export function HomeCategories({items}:{items:TeaItem[]}){const groups=[{name:'绿茶',en:'GREEN TEA',icon:'leaf',copy:'以清鲜、鲜爽的感官印象为起点，认识未经充分发酵的茶。',process:'杀青 · 揉捻 · 干燥',taste:'清鲜 / 豆香 / 回甘'},{name:'红茶',en:'BLACK TEA',icon:'sun',copy:'从花果香与甜润感受出发，认识充分发酵带来的风味变化。',process:'萎凋 · 揉捻 · 发酵 · 干燥',taste:'花果香 / 醇和 / 甜润'}] as const;return <section id="categories" className="home-scroll-section categories-section" tabIndex={-1} aria-labelledby="categories-title"><div className="container"><div className="scroll-section-head"><div><div className="eyebrow">TEA CATEGORIES / 茶叶品类</div><h2 id="categories-title">先分清茶类，再认识一款茶</h2></div><p>本期从绿茶和红茶开始。茶名相同的商品仍按 SKU 与采制批次分别记录。</p></div><div className="category-showcase">{groups.map((group,index)=>{const count=items.filter(item=>item.category===group.name).length;const sample=items.find(item=>item.category===group.name);return <a href={url('/catalog?category='+group.name)} className={'category-story category-'+index} key={group.name}><div className="category-story-top"><span className="category-number">0{index+1}</span><Icon name={group.icon} size={27}/><Badge tone="success">{count} 份公开档案</Badge></div><div className="eyebrow">{group.en}</div><h3>{group.name}</h3><p>{group.copy}</p><dl><div><dt>制作线索</dt><dd>{group.process}</dd></div><div><dt>示例滋味</dt><dd>{sample?.taste.join(' / ')||group.taste}</dd></div></dl><span className="category-link">查看{group.name}档案 <Icon name="arrow" size={17}/></span></a>})}</div></div></section>}

export function HomeReferencesContact(){return <section id="references-contact" className="home-scroll-section references-contact-section" tabIndex={-1} aria-labelledby="references-title"><div className="container"><div className="reference-contact-grid"><article className="reference-column"><div className="eyebrow">REFERENCES / 参考资料</div><h2 id="references-title">内容有来处，也有边界</h2><p className="reference-lead">茶序把资料类型、适用范围、内容版本和审核状态放在同一套说明里，便于回看每一条信息从哪里来。</p><div className="reference-list"><div><Icon name="book"/><span><strong>资料类型</strong><small>茶品字段、冲泡参数与使用说明</small></span></div><div><Icon name="clock"/><span><strong>版本记录</strong><small>按商品、SKU、批次和内容版本区分</small></span></div><div><Icon name="shield"/><span><strong>使用边界</strong><small>演示内容不替代健康建议或交易承诺</small></span></div></div><Button href="/qa" tone="secondary" icon="arrow">查看问茶的资料依据</Button></article><article className="contact-column"><div className="eyebrow">CONTACT / 联系我们</div><h2>从一款具体的茶开始沟通</h2><p>想了解规格、货源或样品，可以先选择对应茶品，再提交一份演示咨询。当前原型不会向任何商家发送信息。</p><div className="contact-actions"><Button href="/catalog" icon="arrow">选择茶品并咨询</Button><Button href="/qa" tone="ghost" icon="chat">先问一问茶</Button></div><div className="contact-meta"><span><Icon name="shield" size={17}/> 联系方式仅用于对应咨询</span><a href={url('/admin')}>进入管理工作台 <Icon name="arrow" size={15}/></a></div></article></div></div></section>}
