// Variant grid adapted from createComponentWithVariants.js; shared plugin data is supported here.
if(components[KIND])return {existing:components[KIND].id,createdNodeIds:[],mutatedNodeIds:[]};
const group=box(page,KIND+' / Documentation',80,Y,1380,KIND==='TeaCard'?500:KIND==='Button'?370:260,'bg',16);
txt(group,KIND,28,18,300,23,'ink','Medium');
const descriptions={Button:'主操作清晰突出。禁用与处理中不触发操作；交互目标至少 44px。',Input:'标签始终可见。错误就近说明，不依赖颜色表达。',Badge:'状态文字与颜色同时表达含义，不把标签误做按钮。',Checkbox:'用户主动确认；默认不勾选。',Notice:'明确解释当前状态，并给出下一步。',TeaCard:'茶类、茶名与商品批次分层；点击进入对应档案。',Step:'当前步骤、已完成和待开始；时间参数清晰可读。'};
txt(group,descriptions[KIND],28,60,1250,13,'muted');
let specs=[];
if(KIND==='Button')for(const tone of ['Primary','Secondary','Ghost'])for(const state of ['Default','Disabled','Loading'])specs.push({variant:'Tone='+tone+', State='+state,tone,state,w:180,h:48});
if(KIND==='Input')for(const state of ['Default','Focused','Error','Disabled'])specs.push({variant:'State='+state,state,w:280,h:52});
if(KIND==='Badge')for(const tone of ['Neutral','Success','Warning','Danger','Accent'])specs.push({variant:'Tone='+tone,tone,w:120,h:28});
if(KIND==='Checkbox')for(const state of ['Unchecked','Checked'])specs.push({variant:'State='+state,state,w:340,h:48});
if(KIND==='Notice')for(const tone of ['Neutral','Warning','Danger'])specs.push({variant:'Tone='+tone,tone,w:380,h:92});
if(KIND==='TeaCard')for(const tone of ['Green','Black'])specs.push({variant:'Tea='+tone,tone,w:400,h:334});
if(KIND==='Step')for(const state of ['Current','Done','Next'])specs.push({variant:'State='+state,state,w:370,h:80});
const built=[];
function prop(comp,node,name,value){const key=comp.addComponentProperty(name,'TEXT',value);node.componentPropertyReferences={characters:key};return key;}
for(const s of specs){const c=tag(figma.createComponent());page.appendChild(c);c.name=s.variant;c.resize(s.w,s.h);c.fills=[paint('surface')];c.setBoundVariable('cornerRadius',vars['radius/8']);c.setSharedPluginData('chaxu','key',KIND+'/'+s.variant);built.push(c);
if(KIND==='Button'){const disabled=s.state==='Disabled',primary=s.tone==='Primary';c.layoutMode='HORIZONTAL';c.primaryAxisAlignItems='CENTER';c.counterAxisAlignItems='CENTER';c.setBoundVariable('paddingLeft',vars['space/20']);c.setBoundVariable('paddingRight',vars['space/20']);c.fills=[paint(disabled?'line':primary?'brand':s.tone==='Secondary'?'surface':'bg')];if(s.tone==='Secondary'){c.strokes=[paint('line')];c.strokeWeight=1;}const label=s.state==='Loading'?'处理中…':'开始体验';const t=txt(c,label,0,0,120,14,disabled?'muted':primary?'surface':'brand','Medium');t.textAutoResize='WIDTH_AND_HEIGHT';prop(c,t,'Label',label);}
if(KIND==='Input'){c.layoutMode='HORIZONTAL';c.primaryAxisAlignItems='MIN';c.counterAxisAlignItems='CENTER';c.setBoundVariable('paddingLeft',vars['space/16']);c.setBoundVariable('paddingRight',vars['space/16']);c.fills=[paint(s.state==='Disabled'?'bg':'surface')];c.strokes=[paint(s.state==='Error'?'danger':s.state==='Focused'?'brand':'line')];c.strokeWeight=s.state==='Focused'?2:1;const t=txt(c,'请输入内容',0,0,240,14,'muted');t.textAutoResize='WIDTH_AND_HEIGHT';prop(c,t,'Label','请输入内容');}
if(KIND==='Badge'){const keys={Neutral:['subtle','brand'],Success:['subtle','brand'],Warning:['warningBg','warning'],Danger:['dangerBg','danger'],Accent:['warningBg','accent']};c.layoutMode='HORIZONTAL';c.primaryAxisAlignItems='CENTER';c.counterAxisAlignItems='CENTER';c.setBoundVariable('paddingLeft',vars['space/12']);c.setBoundVariable('paddingRight',vars['space/12']);c.fills=[paint(keys[s.tone][0])];c.setBoundVariable('cornerRadius',vars['radius/4']);const t=txt(c,({Neutral:'通用资料',Success:'已发布',Warning:'待审核',Danger:'已失效',Accent:'具体批次'})[s.tone],0,0,98,11,keys[s.tone][1]);t.textAutoResize='WIDTH_AND_HEIGHT';prop(c,t,'Label',t.characters);}
if(KIND==='Checkbox'){c.fills=[];const mark=box(c,'Checkbox',0,12,24,24,s.state==='Checked'?'brand':'surface',4);mark.strokes=[paint('line')];if(s.state==='Checked')txt(mark,'✓',4,-1,20,15,'surface');const t=txt(c,'我已阅读并同意上述用途',36,12,290,13,'ink');prop(c,t,'Label',t.characters);}
if(KIND==='Notice'){const fill=s.tone==='Warning'?'warningBg':s.tone==='Danger'?'dangerBg':'subtle';c.fills=[paint(fill)];const t=txt(c,'资料状态说明',16,12,345,14,'ink','Medium');prop(c,t,'Label',t.characters);const b=txt(c,'展示原因，并提供明确可执行的下一步。',16,43,345,12,'muted');prop(c,b,'Body',b.characters);}
if(KIND==='TeaCard'){c.clipsContent=true;c.setBoundVariable('cornerRadius',vars['radius/16']);art(c,0,0,400,178,s.tone==='Green'?'green':'black');chip(c,s.tone==='Green'?'绿茶':'红茶',20,196,'Neutral',55);const t=txt(c,s.tone==='Green'?'西湖龙井':'祁门红茶',20,232,355,21,'ink','Medium',true);prop(c,t,'Label',t.characters);const st=txt(c,s.tone==='Green'?'清鲜豆香 · 从第一杯认识绿茶':'温润甜香 · 认识红茶的滋味',20,271,355,13,'muted');prop(c,st,'Subtitle',st.characters);const meta=txt(c,'查看茶品档案  →',20,303,355,12,'brand');prop(c,meta,'Meta',meta.characters);}
if(KIND==='Step'){c.fills=[paint(s.state==='Current'?'subtle':'surface')];const t=txt(c,s.state==='Done'?'✓ 温杯已完成':s.state==='Current'?'02  注水与浸泡':'03  出汤与品饮',20,12,330,14,'brand','Medium');prop(c,t,'Label',t.characters);const b=txt(c,'查看动作提示与冲泡时长',20,42,330,12,'muted');prop(c,b,'Body',b.characters);}
c.resize(s.w,s.h);if(c.layoutMode!=='NONE'){c.layoutSizingHorizontal='FIXED';c.layoutSizingVertical='FIXED';}
}
const set=tag(figma.combineAsVariants(built,group));set.name=KIND;set.x=28;set.y=108;set.fills=[];const cols=KIND==='Button'?3:KIND==='Input'?4:KIND==='TeaCard'?2:KIND==='Badge'?5:3;built.forEach((c,i)=>{c.x=(i%cols)*(specs[0].w+24);c.y=Math.floor(i/cols)*(specs[0].h+24);});set.resizeWithoutConstraints(Math.min(cols,built.length)*(specs[0].w+24),Math.ceil(built.length/cols)*(specs[0].h+24));
return finish({kind:KIND,setId:set.id,docId:group.id,variantCount:built.length,variants:built.map(c=>({id:c.id,name:c.name})),properties:set.componentPropertyDefinitions});
