const created=[];
const vars=Object.fromEntries((await figma.variables.getLocalVariablesAsync()).map(v=>[v.name,v]));
for(const f of [{family:'Noto Sans SC',style:'Regular'},{family:'Noto Sans SC',style:'Medium'},{family:'Noto Sans SC',style:'Bold'},{family:'Noto Serif SC',style:'Medium'},{family:'Inter',style:'Regular'}])await figma.loadFontAsync(f);
const ds=figma.root.children.find(p=>p.name==='00 · 设计系统');
if(ds)await figma.setCurrentPageAsync(ds);
const components=ds?Object.fromEntries(ds.findAll(n=>n.type==='COMPONENT_SET').map(n=>[n.name,n])):{};
const page=figma.root.children.find(p=>p.name===PAGE);
if(!page)throw new Error('Missing page '+PAGE);
await figma.setCurrentPageAsync(page);
function resolvedColor(v){let value=Object.values(v.valuesByMode)[0];let guard=0;while(value.type==='VARIABLE_ALIAS'&&guard++<5){v=Object.values(vars).find(x=>x.id===value.id);value=Object.values(v.valuesByMode)[0];}return {r:value.r,g:value.g,b:value.b};}
const paint=(key)=>figma.variables.setBoundVariableForPaint({type:'SOLID',color:resolvedColor(vars['color/'+key])},'color',vars['color/'+key]);
function tag(n){n.setSharedPluginData('chaxu','run','chaxu-prototype-20260910');created.push(n.id);return n;}
function box(p,name,x,y,w,h,fill='surface',radius=0){const n=tag(figma.createFrame());n.name=name;p.appendChild(n);n.x=x;n.y=y;n.resize(w,h);n.fills=fill?[paint(fill)]:[];if(vars['radius/'+radius])n.setBoundVariable('cornerRadius',vars['radius/'+radius]);else n.cornerRadius=radius;n.clipsContent=false;return n;}
function rect(p,x,y,w,h,fill,radius=0){const n=tag(figma.createRectangle());p.appendChild(n);n.name='Shape';n.x=x;n.y=y;n.resize(w,h);n.fills=[paint(fill)];if(vars['radius/'+radius])n.setBoundVariable('cornerRadius',vars['radius/'+radius]);return n;}
function ellipse(p,x,y,w,h,fill){const n=tag(figma.createEllipse());p.appendChild(n);n.name='Tea illustration';n.x=x;n.y=y;n.resize(w,h);n.fills=[paint(fill)];return n;}
function txt(p,value,x,y,w,size=15,color='ink',weight='Regular',serif=false){const n=tag(figma.createText());p.appendChild(n);n.name=value.slice(0,35);n.fontName={family:serif?'Noto Serif SC':'Noto Sans SC',style:weight};n.fontSize=size;n.lineHeight={unit:'PIXELS',value:Math.ceil(size*1.6)};n.fills=[paint(color)];n.characters=value;n.resize(w,Math.ceil(size*1.6));n.textAutoResize='HEIGHT';n.x=x;n.y=y;return n;}
function link(n,to){n.setSharedPluginData('chaxu','to',to);n.name+=' → '+to;return n;}
function component(p,setName,variant,label,x,y,w,h,to){const set=components[setName];if(!set)throw new Error('Missing component '+setName);const base=set.children.find(c=>c.name===variant)||set.children[0];const n=tag(base.createInstance());p.appendChild(n);n.x=x;n.y=y;if(w&&h)n.resize(w,h);const key=Object.keys(n.componentProperties).find(k=>k.startsWith('Label#'));if(key&&label!==null)n.setProperties({[key]:label});if(to)link(n,to);return n;}
function btn(p,label,x,y,w=144,to=null,tone='Primary'){return component(p,'Button','Tone='+tone+', State=Default',label,x,y,w,48,to);}
function chip(p,label,x,y,tone='Neutral',w=86,to=null){return component(p,'Badge','Tone='+tone,label,x,y,w,28,to);}
function input(p,label,value,x,y,w=400,state='Default',to=null){txt(p,label,x,y,w,13,'muted');return component(p,'Input','State='+state,value,x,y+28,w,52,to);}
function rule(p,x,y,w){return rect(p,x,y,w,1,'line');}
function notice(p,title,body,x,y,w,tone='Neutral'){const fill=tone==='Warning'?'warningBg':tone==='Danger'?'dangerBg':'subtle';const ink=tone==='Warning'?'warning':tone==='Danger'?'danger':'brand';const n=box(p,'Notice',x,y,w,88,fill,8);txt(n,title,20,13,w-40,14,ink,'Medium');txt(n,body,20,40,w-40,12,ink);return n;}
function art(p,x,y,w,h,variant='green'){const n=box(p,'原生矢量茶境插画',x,y,w,h,variant==='green'?'subtle':'warningBg',16);n.clipsContent=true;ellipse(n,w*.58,-h*.24,w*.7,w*.7,'artSand');ellipse(n,-w*.28,h*.58,w*1.6,h*.82,variant==='green'?'artSage':'artTea');ellipse(n,w*.04,h*.76,w*1.1,h*.6,'brand');const cx=w*.51,cy=h*.62;ellipse(n,cx-w*.22,cy+h*.12,w*.47,h*.13,'artSand');const cup=box(n,'茶盏',cx-w*.18,cy-h*.1,w*.37,h*.25,'surface',16);ellipse(n,cx-w*.19,cy-h*.14,w*.39,h*.12,'surface');ellipse(n,cx-w*.155,cy-h*.12,w*.32,h*.07,'artTea');for(let i=0;i<3;i++){const leaf=ellipse(n,w*(.12+i*.07),h*(.34-i*.075),w*.15,h*.045,'brand');leaf.rotation=-35-i*15;}txt(n,'一叶 · 一盏',w*.09,h*.1,w*.42,Math.max(11,w*.039),'brand','Medium',true);return n;}
function publicShell(f,active='发现茶',mobile=false){const w=f.width;if(mobile){txt(f,'茶序',22,14,110,25,'brand','Medium',true);chip(f,'演示',w-79,24,'Neutral',56);rule(f,0,76,w);return;}
txt(f,'茶序',64,17,110,30,'brand','Medium',true);txt(f,'CHA XU',151,34,82,10,'muted');const tabs=[['发现茶','home'],['茶品档案','catalog'],['泡一杯茶','brew'],['问茶','qa']];tabs.forEach(([a,b],i)=>{const t=txt(f,a,440+i*125,31,110,14,active===a?'brand':'muted',active===a?'Medium':'Regular');link(t,b);if(active===a)rect(f,440+i*125,67,42,2,'brand');});chip(f,'交互演示',1130,25,'Neutral',92);btn(f,'开始选茶',1240,16,136,'catalog');rule(f,0,88,w);}
function foot(f,mobile=false){const y=f.height-40;rule(f,mobile?20:64,y-14,f.width-(mobile?40:128));txt(f,'茶序 · 产品交互原型',mobile?20:64,y,mobile?210:300,10,'muted');if(!mobile)txt(f,'示例资料仅供体验，非真实功效、报价或服务承诺',820,y,550,10,'muted');}
function adminShell(f,title,active='工作概览'){const side=box(f,'后台导航',0,0,240,f.height,'dark');txt(side,'茶序',28,26,140,28,'surface','Medium',true);txt(side,'内容与运营工作台',28,80,180,12,'artSage');const items=[['工作概览','admin-home'],['内容管理','admin-content'],['导入中心','admin-import'],['审核发布','admin-review'],['咨询线索','admin-leads'],['账号与权限','admin-users']];items.forEach(([a,b],i)=>{if(a===active)box(side,'当前栏目',16,137+i*58,208,46,'brand',8);link(txt(side,a,32,146+i*58,170,14,a===active?'surface':'artSage',a===active?'Medium':'Regular'),b);});link(txt(side,'← 返回用户端',28,f.height-82,175,13,'artSage'),'home');txt(f,title,280,26,660,22,'ink','Medium');chip(f,'演示工作区',1100,28,'Neutral',112);link(txt(f,'林清 · 审核人',1240,29,180,13,'muted'),'admin-users');rule(f,240,88,f.width-240);}
function title(f,kicker,heading,subtitle,x=80,y=120,w=900){txt(f,kicker,x,y,w,11,'muted');txt(f,heading,x,y+29,w,32,'ink','Medium',true);if(subtitle)txt(f,subtitle,x,y+91,w,14,'muted');}
function finish(extra={}){return {createdNodeIds:created,mutatedNodeIds:[],...extra};}
